services:
  # Relational Database
  orders-database:
    image: postgres:15-alpine
    container_name: orders-database
    env_file:
      - ./orders-service/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  audit-db:
    image: mongo:6.0-alpine
    container_name: audit-db
    env_file:
      - ./audit-service/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_NAME}
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: orders-rabbitmq
    env_file:
      - ./app-gateway/.env
    ports:
      - "5672:5672"
      - "15672:15672" # UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  mongodata:
  rabbitdata: